"""adiciona delete cascade as tabelas

Revision ID: 11d08fe1a70c
Revises: abd26ef5eef3
Create Date: 2026-09-11 15:19:02.244076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d08fe1a70c'
down_revision: Union[str, Sequence[str], None] = 'abd26ef5eef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'alunos', ['usuario_id'])
    op.create_foreign_key(None, 'alunos', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.add_column('mediadores', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'mediadores', ['usuario_id'])
    op.create_foreign_key(None, 'mediadores', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.add_column('professores', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'professores', ['usuario_id'])
    op.create_foreign_key(None, 'professores', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professores', type_='foreignkey')
    op.drop_constraint(None, 'professores', type_='unique')
    op.drop_column('professores', 'usuario_id')
    op.drop_constraint(None, 'mediadores', type_='foreignkey')
    op.drop_constraint(None, 'mediadores', type_='unique')
    op.drop_column('mediadores', 'usuario_id')
    op.drop_constraint(None, 'alunos', type_='foreignkey')
    op.drop_constraint(None, 'alunos', type_='unique')
    op.drop_column('alunos', 'usuario_id')
    # ### end Alembic commands ###
