"""add ondelete cascade on atendimentos

Revision ID: 1b585ee0608c
Revises: 64eaa13af5d7
Create Date: 2026-10-01 09:25:22.591879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b585ee0608c'
down_revision: Union[str, Sequence[str], None] = '64eaa13af5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('atendimentos_id_solicitacao_fkey'), 'atendimentos', type_='foreignkey')
    op.create_foreign_key(None, 'atendimentos', 'solicitacoes', ['id_solicitacao'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atendimentos', type_='foreignkey')
    op.create_foreign_key(op.f('atendimentos_id_solicitacao_fkey'), 'atendimentos', 'solicitacoes', ['id_solicitacao'], ['id'])
    # ### end Alembic commands ###
