"""add ondelete cascade in solicitacoes

Revision ID: 1d6b731f6c4e
Revises: bd01c9cf39c5
Create Date: 2026-09-28 16:22:44.546174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6b731f6c4e'
down_revision: Union[str, Sequence[str], None] = 'bd01c9cf39c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('solicitacoes_id_aluno_fkey'), 'solicitacoes', type_='foreignkey')
    op.create_foreign_key(None, 'solicitacoes', 'alunos', ['id_aluno'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitacoes', type_='foreignkey')
    op.create_foreign_key(op.f('solicitacoes_id_aluno_fkey'), 'solicitacoes', 'alunos', ['id_aluno'], ['id'])
    # ### end Alembic commands ###
