"""init_postgresql

Revision ID: 1d82704f7e74
Revises: 
Create Date: 2026-09-05 12:05:26.824678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1d82704f7e74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mediador')
    op.drop_table('professor')
    op.alter_column('disciplinas', 'nome',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.alter_column('turmas', 'curso',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.alter_column('turmas', 'turno',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10),
               existing_nullable=False)
    op.alter_column('usuarios', 'nome',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.alter_column('usuarios', 'matricula',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('usuarios', 'senha',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'usuarios', ['email'])
    op.create_unique_constraint(None, 'usuarios', ['matricula'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.alter_column('usuarios', 'senha',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('usuarios', 'matricula',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('usuarios', 'nome',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('turmas', 'turno',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('turmas', 'curso',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('disciplinas', 'nome',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_table('professor',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], name=op.f('professor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('professor_pkey'))
    )
    op.create_table('mediador',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], name=op.f('mediador_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mediador_pkey'))
    )
    # ### end Alembic commands ###
