"""atualiza tabela solicitacoes

Revision ID: 41f62b8f577c
Revises: d596a2036650
Create Date: 2026-10-01 17:40:25.707553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '41f62b8f577c'
down_revision: Union[str, Sequence[str], None] = 'd596a2036650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitacoes', sa.Column('tipo_suporte', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('solicitacoes', sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.drop_column('solicitacoes', 'observacoes')
    op.drop_column('solicitacoes', 'suporte')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitacoes', sa.Column('suporte', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('solicitacoes', sa.Column('observacoes', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('solicitacoes', 'descricao')
    op.drop_column('solicitacoes', 'tipo_suporte')
    # ### end Alembic commands ###
