"""adiciona tabela de cursos

Revision ID: 56147199259b
Revises: d47c2694b718
Create Date: 2026-09-11 17:37:34.230177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '56147199259b'
down_revision: Union[str, Sequence[str], None] = 'd47c2694b718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('turmas', sa.Column('curso_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'turmas', 'cursos', ['curso_id'], ['id'])
    op.drop_column('turmas', 'curso')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turmas', sa.Column('curso', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'turmas', type_='foreignkey')
    op.drop_column('turmas', 'curso_id')
    op.drop_table('cursos')
    # ### end Alembic commands ###
