"""add ondelete cascade on alunos_atendimentos

Revision ID: 64eaa13af5d7
Revises: de749e12f8b4
Create Date: 2026-10-01 09:24:04.763906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64eaa13af5d7'
down_revision: Union[str, Sequence[str], None] = 'de749e12f8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('aluno_atendimentos_aluno_id_fkey'), 'aluno_atendimentos', type_='foreignkey')
    op.drop_constraint(op.f('aluno_atendimentos_atendimento_id_fkey'), 'aluno_atendimentos', type_='foreignkey')
    op.create_foreign_key(None, 'aluno_atendimentos', 'alunos', ['aluno_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'aluno_atendimentos', 'atendimentos', ['atendimento_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aluno_atendimentos', type_='foreignkey')
    op.drop_constraint(None, 'aluno_atendimentos', type_='foreignkey')
    op.create_foreign_key(op.f('aluno_atendimentos_atendimento_id_fkey'), 'aluno_atendimentos', 'atendimentos', ['atendimento_id'], ['id'])
    op.create_foreign_key(op.f('aluno_atendimentos_aluno_id_fkey'), 'aluno_atendimentos', 'alunos', ['aluno_id'], ['id'])
    # ### end Alembic commands ###
