"""permitir colunas null

Revision ID: 6e501f7a1802
Revises: 3b9c4d5e6f7a
Create Date: 2026-09-10 22:33:52.412945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e501f7a1802'
down_revision: Union[str, Sequence[str], None] = '3b9c4d5e6f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atendimentos', 'id_professor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('atendimentos', 'id_turma',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('atendimentos', 'id_disciplina',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('atendimentos', 'id_horario',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('solicitacoes', 'id_mediador',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solicitacoes', 'id_mediador',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('atendimentos', 'id_horario',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('atendimentos', 'id_disciplina',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('atendimentos', 'id_turma',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('atendimentos', 'id_professor',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
