"""criando tabelas

Revision ID: 6fe445d2007b
Revises: 
Create Date: 2026-09-04 11:31:23.951488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic
revision: str = '6fe445d2007b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_termino', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('mensagem', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('lido_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('ano', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turno', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('matricula', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('senha', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horario_salas',
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.PrimaryKeyConstraint('horario_id', 'sala_id')
    )
    op.create_table('mediadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('LIBRAS', 'BRAILE', 'ACOMPANHAMENTO', 'MOBILIDADE', 'TRANSTORNOS_ESPECIFICOS', 'OUTRO', name='tipomediador'), nullable=False),
    sa.Column('apoio_descricao', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_notificacoes',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('notificacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notificacao_id'], ['notificacoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'notificacao_id')
    )
    op.create_table('professor_disciplinas',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('professor_id', 'disciplina_id')
    )
    op.create_table('professor_turmas',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('professor_id', 'turma_id')
    )
    op.create_table('solicitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_mediador', sa.Integer(), nullable=False),
    sa.Column('observacoes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'RECUSADO', 'CANCELADO', name='statussolicitacao'), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['id_mediador'], ['mediadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.Column('id_turma', sa.Integer(), nullable=False),
    sa.Column('id_disciplina', sa.Integer(), nullable=False),
    sa.Column('id_solicitacao', sa.Integer(), nullable=True),
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.Column('id_sala', sa.Integer(), nullable=True),
    sa.Column('data_atendimento', sa.Date(), nullable=False),
    sa.Column('tipo_atendimento', sa.Enum('TAI', 'TAL', name='tipoatendimento'), nullable=False),
    sa.Column('modalidade', sa.Enum('PRESENCIAL', 'REMOTO', name='modalidadeaula'), nullable=False),
    sa.Column('assunto', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('relatorio', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('status', sa.Enum('AGENDADO', 'CONCLUIDO', 'CANCELADO', name='statusatendimento'), nullable=False),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['id_horario'], ['horarios.id'], ),
    sa.ForeignKeyConstraint(['id_professor'], ['professores.id'], ),
    sa.ForeignKeyConstraint(['id_sala'], ['salas.id'], ),
    sa.ForeignKeyConstraint(['id_solicitacao'], ['solicitacoes.id'], ),
    sa.ForeignKeyConstraint(['id_turma'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_solicitacao')
    )
    op.create_table('aluno_atendimentos',
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.PrimaryKeyConstraint('aluno_id', 'atendimento_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aluno_atendimentos')
    op.drop_table('atendimentos')
    op.drop_table('solicitacoes')
    op.drop_table('professor_turmas')
    op.drop_table('professor_disciplinas')
    op.drop_table('usuario_notificacoes')
    op.drop_table('professores')
    op.drop_table('mediadores')
    op.drop_table('horario_salas')
    op.drop_table('alunos')
    op.drop_table('usuarios')
    op.drop_table('turmas')
    op.drop_table('salas')
    op.drop_table('notificacoes')
    op.drop_table('horarios')
    op.drop_table('disciplinas')
    # ### end Alembic commands ###
