"""adiciona coluna codigo em turma

Revision ID: 7122dc0abf1f
Revises: 56147199259b
Create Date: 2026-09-11 17:42:46.765322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7122dc0abf1f'
down_revision: Union[str, Sequence[str], None] = '56147199259b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turmas', sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turmas', 'codigo')
    # ### end Alembic commands ###
