"""add ondelete cascade on professor_turmas

Revision ID: a32d087e1ca4
Revises: 1d6b731f6c4e
Create Date: 2026-09-28 16:31:31.900028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32d087e1ca4'
down_revision: Union[str, Sequence[str], None] = '1d6b731f6c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('professor_turmas_professor_id_fkey'), 'professor_turmas', type_='foreignkey')
    op.drop_constraint(op.f('professor_turmas_turma_id_fkey'), 'professor_turmas', type_='foreignkey')
    op.create_foreign_key(None, 'professor_turmas', 'turmas', ['turma_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'professor_turmas', 'professores', ['professor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professor_turmas', type_='foreignkey')
    op.drop_constraint(None, 'professor_turmas', type_='foreignkey')
    op.create_foreign_key(op.f('professor_turmas_turma_id_fkey'), 'professor_turmas', 'turmas', ['turma_id'], ['id'])
    op.create_foreign_key(op.f('professor_turmas_professor_id_fkey'), 'professor_turmas', 'professores', ['professor_id'], ['id'])
    # ### end Alembic commands ###
