"""add ondelete cascade in usurio_notificacoes

Revision ID: bd01c9cf39c5
Revises: 4c0d5e6f7a8b
Create Date: 2026-09-28 16:20:44.182740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd01c9cf39c5'
down_revision: Union[str, Sequence[str], None] = '4c0d5e6f7a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('usuario_notificacoes_usuario_id_fkey'), 'usuario_notificacoes', type_='foreignkey')
    op.drop_constraint(op.f('usuario_notificacoes_notificacao_id_fkey'), 'usuario_notificacoes', type_='foreignkey')
    op.create_foreign_key(None, 'usuario_notificacoes', 'notificacoes', ['notificacao_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'usuario_notificacoes', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario_notificacoes', type_='foreignkey')
    op.drop_constraint(None, 'usuario_notificacoes', type_='foreignkey')
    op.create_foreign_key(op.f('usuario_notificacoes_notificacao_id_fkey'), 'usuario_notificacoes', 'notificacoes', ['notificacao_id'], ['id'])
    op.create_foreign_key(op.f('usuario_notificacoes_usuario_id_fkey'), 'usuario_notificacoes', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###
