"""remove colunas usuario_id

Revision ID: d47c2694b718
Revises: 11d08fe1a70c
Create Date: 2026-09-11 16:16:28.596714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47c2694b718'
down_revision: Union[str, Sequence[str], None] = '11d08fe1a70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('alunos_usuario_id_key'), 'alunos', type_='unique')
    op.drop_constraint(op.f('alunos_id_fkey'), 'alunos', type_='foreignkey')
    op.drop_constraint(op.f('alunos_usuario_id_fkey'), 'alunos', type_='foreignkey')
    op.create_foreign_key(None, 'alunos', 'usuarios', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('alunos', 'usuario_id')
    op.drop_constraint(op.f('mediadores_usuario_id_key'), 'mediadores', type_='unique')
    op.drop_constraint(op.f('mediadores_usuario_id_fkey'), 'mediadores', type_='foreignkey')
    op.drop_constraint(op.f('mediadores_id_fkey'), 'mediadores', type_='foreignkey')
    op.create_foreign_key(None, 'mediadores', 'usuarios', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('mediadores', 'usuario_id')
    op.drop_constraint(op.f('professores_usuario_id_key'), 'professores', type_='unique')
    op.drop_constraint(op.f('professores_usuario_id_fkey'), 'professores', type_='foreignkey')
    op.drop_constraint(op.f('professores_id_fkey'), 'professores', type_='foreignkey')
    op.create_foreign_key(None, 'professores', 'usuarios', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('professores', 'usuario_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professores', sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'professores', type_='foreignkey')
    op.create_foreign_key(op.f('professores_id_fkey'), 'professores', 'usuarios', ['id'], ['id'])
    op.create_foreign_key(op.f('professores_usuario_id_fkey'), 'professores', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('professores_usuario_id_key'), 'professores', ['usuario_id'], postgresql_nulls_not_distinct=False)
    op.add_column('mediadores', sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mediadores', type_='foreignkey')
    op.create_foreign_key(op.f('mediadores_id_fkey'), 'mediadores', 'usuarios', ['id'], ['id'])
    op.create_foreign_key(op.f('mediadores_usuario_id_fkey'), 'mediadores', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('mediadores_usuario_id_key'), 'mediadores', ['usuario_id'], postgresql_nulls_not_distinct=False)
    op.add_column('alunos', sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'alunos', type_='foreignkey')
    op.create_foreign_key(op.f('alunos_usuario_id_fkey'), 'alunos', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('alunos_id_fkey'), 'alunos', 'usuarios', ['id'], ['id'])
    op.create_unique_constraint(op.f('alunos_usuario_id_key'), 'alunos', ['usuario_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
