"""add suporte e id_disciplina em solicitacao

Revision ID: d596a2036650
Revises: 1b585ee0608c
Create Date: 2026-10-01 10:12:48.008297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd596a2036650'
down_revision: Union[str, Sequence[str], None] = '1b585ee0608c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitacoes', sa.Column('id_disciplina', sa.Integer(), nullable=False))
    op.add_column('solicitacoes', sa.Column('suporte', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.create_foreign_key(None, 'solicitacoes', 'disciplinas', ['id_disciplina'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitacoes', type_='foreignkey')
    op.drop_column('solicitacoes', 'suporte')
    op.drop_column('solicitacoes', 'id_disciplina')
    # ### end Alembic commands ###
